use super::*;
pub(super) fn mysql_service(name: &str) -> ServiceConfig {
    ServiceConfig {
        name: name.to_owned(),
        kind: Kind::Database,
        driver: Driver::Mysql,
        image: "mysql:8.0".to_owned(),
        host: "127.0.0.1".to_owned(),
        port: 3306,
        database: Some("app".to_owned()),
        username: Some("root".to_owned()),
        password: Some("secret".to_owned()),
        bucket: None,
        access_key: None,
        secret_key: None,
        api_key: None,
        region: None,
        scheme: None,
        domain: None,
        domains: None,
        container_port: None,
        smtp_port: None,
        volumes: None,
        env: None,
        command: None,
        depends_on: None,
        seed_file: None,
        health_path: None,
        health_statuses: None,
        localhost_tls: false,
        octane: false,
        php_extensions: None,
        trust_container_ca: false,
        env_mapping: None,
        container_name: None,
        resolved_container_name: Some(format!("test-{name}")),
    }
}

pub(super) fn app_service(name: &str, domain: &str, port: u16, driver: Driver) -> ServiceConfig {
    ServiceConfig {
        name: name.to_owned(),
        kind: Kind::App,
        driver,
        image: "dunglas/frankenphp:php8.5".to_owned(),
        host: "127.0.0.1".to_owned(),
        port,
        domain: Some(domain.to_owned()),
        domains: None,
        container_port: None,
        smtp_port: None,
        database: None,
        username: None,
        password: None,
        bucket: None,
        access_key: None,
        secret_key: None,
        api_key: None,
        region: None,
        scheme: None,
        volumes: None,
        env: None,
        command: None,
        depends_on: None,
        seed_file: None,
        health_path: None,
        health_statuses: None,
        localhost_tls: false,
        octane: false,
        php_extensions: None,
        trust_container_ca: false,
        env_mapping: None,
        container_name: None,
        resolved_container_name: None,
    }
}
