#[cfg(test)]
mod tests;

mod caddy_gateway_document;
mod caddy_gateway_provider;
#[cfg(unix)]
mod caddy_unix_admin_client;
mod engine_gateway_port_probe;
mod gateway_configuration;
mod gateway_configuration_action;
mod gateway_document_loader;
mod gateway_error;
mod gateway_plane_options;
mod gateway_plane_result;
mod gateway_port_availability;
mod gateway_port_probe;
mod gateway_readiness_options;
mod gateway_reconcile_action;
mod gateway_reconcile_options;
mod gateway_reconcile_result;
mod gateway_route;
mod gateway_runtime_asset_error;
mod gateway_runtime_asset_options;
mod gateway_runtime_assets;
mod gateway_snapshot;
mod global_gateway_request;
mod global_gateway_request_options;
mod localhost_resolver;
mod preflight_gateway_ports;
mod prepare_gateway_runtime_assets;
mod reconcile_gateway;
mod reconcile_gateway_configuration;
mod reconcile_gateway_plane;
mod render_caddy_document;
mod store_active_gateway_certificate_generation;
mod store_caddy_bootstrap;
mod stored_gateway_bootstrap_paths;
mod system_gateway_port_probe;
mod system_localhost_resolver;
mod verify_gateway_ports_available;
mod verify_stackctl_localhost_resolution;
mod wait_for_gateway_certificate_generation;
mod wait_for_gateway_ready;

pub(crate) use caddy_gateway_document::CaddyGatewayDocument;
pub(crate) use caddy_gateway_provider::CaddyGatewayProvider;
#[cfg(unix)]
pub(crate) use caddy_unix_admin_client::CaddyUnixAdminClient;
pub(crate) use engine_gateway_port_probe::EngineGatewayPortProbe;
pub(crate) use gateway_configuration::{GatewayConfiguration, GatewayFuture};
pub(crate) use gateway_configuration_action::GatewayConfigurationAction;
pub(crate) use gateway_document_loader::GatewayDocumentLoader;
pub(crate) use gateway_error::GatewayError;
pub(crate) use gateway_plane_options::GatewayPlaneOptions;
pub(crate) use gateway_plane_result::GatewayPlaneResult;
pub(crate) use gateway_port_availability::GatewayPortAvailability;
pub(crate) use gateway_port_probe::GatewayPortProbe;
pub(crate) use gateway_readiness_options::GatewayReadinessOptions;
pub(crate) use gateway_reconcile_action::GatewayReconcileAction;
pub(crate) use gateway_reconcile_options::GatewayReconcileOptions;
pub(crate) use gateway_reconcile_result::GatewayReconcileResult;
pub(crate) use gateway_route::GatewayRoute;
pub(crate) use gateway_runtime_asset_error::GatewayRuntimeAssetError;
pub(crate) use gateway_runtime_asset_options::GatewayRuntimeAssetOptions;
pub(crate) use gateway_runtime_assets::GatewayRuntimeAssets;
pub(super) use gateway_runtime_assets::{
    CONTAINER_ADMIN_SOCKET_PATH, CONTAINER_CERTIFICATE_PATH, CONTAINER_PRIVATE_KEY_PATH,
};
pub(crate) use gateway_snapshot::GatewaySnapshot;
pub(crate) use global_gateway_request::global_gateway_request;
pub(crate) use global_gateway_request_options::GlobalGatewayRequestOptions;
pub(crate) use localhost_resolver::LocalhostResolver;
pub(crate) use preflight_gateway_ports::preflight_gateway_ports;
pub(crate) use prepare_gateway_runtime_assets::prepare_gateway_runtime_assets;
pub(crate) use reconcile_gateway::reconcile_gateway;
pub(crate) use reconcile_gateway_configuration::reconcile_gateway_configuration;
pub(crate) use reconcile_gateway_plane::reconcile_gateway_plane;
pub(crate) use render_caddy_document::render_caddy_document;
pub(crate) use store_active_gateway_certificate_generation::store_active_gateway_certificate_generation;
pub(crate) use store_caddy_bootstrap::store_caddy_bootstrap;
pub(crate) use stored_gateway_bootstrap_paths::StoredGatewayBootstrapPaths;
pub(crate) use system_gateway_port_probe::SystemGatewayPortProbe;
pub(crate) use system_localhost_resolver::SystemLocalhostResolver;
pub(crate) use verify_gateway_ports_available::verify_gateway_ports_available;
pub(crate) use verify_stackctl_localhost_resolution::verify_stackctl_localhost_resolution;
pub(crate) use wait_for_gateway_certificate_generation::wait_for_gateway_certificate_generation;
pub(crate) use wait_for_gateway_ready::wait_for_gateway_ready;
