use crate::config::{Driver, Kind, ServiceConfig};

pub(super) fn app_service() -> ServiceConfig {
    ServiceConfig {
        name: "app".to_owned(),
        kind: Kind::App,
        driver: Driver::Frankenphp,
        image: "dunglas/frankenphp:php8.5".to_owned(),
        host: "127.0.0.1".to_owned(),
        port: 33065,
        database: None,
        username: None,
        password: None,
        bucket: None,
        access_key: None,
        secret_key: None,
        api_key: None,
        region: None,
        scheme: None,
        domain: Some("acme-api.helm".to_owned()),
        domains: None,
        container_port: Some(80),
        smtp_port: None,
        volumes: None,
        env: None,
        command: None,
        depends_on: None,
        seed_file: None,
        health_path: None,
        health_statuses: None,
        localhost_tls: false,
        octane: false,
        php_extensions: None,
        trust_container_ca: false,
        env_mapping: None,
        container_name: Some("acme-api-app".to_owned()),
        resolved_container_name: Some("acme-api-app".to_owned()),
    }
}
